name: main_workflow
on:
  push:
    branches:
      - send_email
jobs:
  # linter-execution:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node: [10, 12]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Setting node version
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node }}
  #     - name: Linter execution
  #       uses: github/super-linter@v4
  #       env:
  #         DEFAULT_BRANCH: nodejs_example
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         LINTER_RULES_PATH: /
  #         JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
  #         VALIDATE_JAVASCRIPT_ES: true
  test-ejecution:
    # needs: linter-execution
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: jest test
        id: test 
        run: npm install jest && npm test
        continue-on-error: true
      - name: Send email
        if: steps.test.outcome != 'success'
        run: echo "Test failed by Vicent"
          # uses: dawidd6/action-send-mail@v3
          # with:
          #   server_address: vicentesteve2002@gmail.com
          #   server_port: 465
          #   subject: Github Actions job result
          #   username: ${{secrets.MAIL_USERNAME}}
          #   password: ${{secrets.MAIL_PASSWORD}}
          #   to: esteve.ferre,vicent@gmail.com
          #   from: Vicent Esteve
          #   body: Build job of ${{github.repository}} completed successfully!
  environment_test_execution:
    # needs: [linter-execution, test-ejecution]
    strategy:
      matrix:
        include:
          - DESTINATION_PERSON: "2DAW"
    runs-on: ubuntu-latest
    steps:
      - name: Hellow enviroment
        uses: adeloyedeji/github-actions-hello@v1.0
        with: 
          who-to-greet: ${{matrix.DESTINATION_PERSON}}

